when:
  - event: push
    branch: main

steps:
  - name: check
    image: node:24
    commands:
      - npm install --global bun@1.3.2
      - make setup
      - make lint
      - make test
      - make build
