name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      #   with:
      #       lfs: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      # - uses: oven-sh/setup-bun@v2
      # - uses: Swatinem/rust-cache@v2
      # - run: make setup
      - run: make lint
      - run: make test
